import type { DrumFamily, KitDef, SoundDef, SynthLayer } from "./types";

function L(partial: SynthLayer): SynthLayer {
  return partial;
}

function sound(
  id: string,
  name: string,
  family: DrumFamily,
  acoustic: boolean,
  duration: number,
  genres: string[],
  character: string[],
  layers: SynthLayer[],
): SoundDef {
  return { id, name, family, acoustic, duration, genres, character, layers };
}

export const SOUND_LIBRARY: SoundDef[] = [
  sound("808-kick", "808 Long", "kick", false, 2.1, ["electronic", "hiphop", "trap"], ["deep", "sub"], [
    L({ kind: "sine", gain: 0.95, startHz: 98, endHz: 42, pitchDecay: 9, ampDecay: 3.2, attack: 0.002, drive: 0.35 }),
    L({ kind: "click", gain: 0.18, startHz: 1800, ampDecay: 70, attack: 0.0004 }),
    L({ kind: "sine", gain: 0.22, startHz: 52, endHz: 38, pitchDecay: 4, ampDecay: 2.4 }),
  ]),
  sound("808-kick-punch", "808 Punch", "kick", false, 1.4, ["electronic", "trap", "pop"], ["punchy"], [
    L({ kind: "sine", gain: 0.92, startHz: 140, endHz: 48, pitchDecay: 14, ampDecay: 5.5, attack: 0.001, drive: 0.42 }),
    L({ kind: "click", gain: 0.28, startHz: 2400, ampDecay: 90, attack: 0.0003 }),
  ]),
  sound("808-sub", "808 Sub", "kick", false, 2.4, ["trap", "hiphop"], ["sub", "dark"], [
    L({ kind: "sine", gain: 1, startHz: 72, endHz: 34, pitchDecay: 6, ampDecay: 2.4, attack: 0.004, drive: 0.2 }),
  ]),
  sound("909-kick", "909 Kick", "kick", false, 1.1, ["electronic", "house", "techno"], ["punchy", "classic"], [
    L({ kind: "sine", gain: 0.88, startHz: 165, endHz: 48, pitchDecay: 18, ampDecay: 7.5, attack: 0.0008, drive: 0.28 }),
    L({ kind: "click", gain: 0.42, startHz: 3200, ampDecay: 110, attack: 0.0002 }),
    L({ kind: "noise", gain: 0.08, ampDecay: 40, hp: 4000, lp: 9000, noiseColor: 1 }),
  ]),
  sound("909-kick-hard", "909 Hard", "kick", false, 0.9, ["techno", "house"], ["hard", "punchy"], [
    L({ kind: "sine", gain: 0.9, startHz: 190, endHz: 50, pitchDecay: 22, ampDecay: 9, drive: 0.55 }),
    L({ kind: "click", gain: 0.55, startHz: 4000, ampDecay: 130 }),
  ]),
  sound("studio-kick", "Studio Kick", "kick", true, 1.2, ["studio", "pop", "hiphop"], ["tight", "round"], [
    L({ kind: "sine", gain: 0.82, startHz: 92, endHz: 52, pitchDecay: 12, ampDecay: 6.5, drive: 0.18 }),
    L({ kind: "sine", gain: 0.28, startHz: 180, endHz: 90, pitchDecay: 20, ampDecay: 14 }),
    L({ kind: "click", gain: 0.32, startHz: 2800, ampDecay: 85 }),
    L({ kind: "noise", gain: 0.1, ampDecay: 28, hp: 200, lp: 800, noiseColor: 0.3 }),
  ]),
  sound("vintage-kick", "Vintage Kick", "kick", true, 1.5, ["studio", "hiphop"], ["warm", "round"], [
    L({ kind: "sine", gain: 0.9, startHz: 78, endHz: 46, pitchDecay: 8, ampDecay: 4.2, drive: 0.45 }),
    L({ kind: "sine", gain: 0.2, startHz: 140, endHz: 70, pitchDecay: 10, ampDecay: 8 }),
    L({ kind: "click", gain: 0.16, startHz: 1600, ampDecay: 60 }),
  ]),
  sound("acoustic-kick", "Acoustic Beater", "kick", true, 1.1, ["studio", "pop", "indie"], ["acoustic", "beater"], [
    L({ kind: "sine", gain: 0.78, startHz: 88, endHz: 55, pitchDecay: 16, ampDecay: 7, drive: 0.12 }),
    L({ kind: "noise", gain: 0.22, ampDecay: 22, hp: 800, lp: 4500, noiseColor: 0.7 }),
    L({ kind: "click", gain: 0.4, startHz: 3500, ampDecay: 95 }),
  ]),
  sound("house-kick", "House Thump", "kick", false, 0.85, ["house", "pop"], ["thump", "punchy"], [
    L({ kind: "sine", gain: 0.9, startHz: 130, endHz: 50, pitchDecay: 20, ampDecay: 8.5, drive: 0.3 }),
    L({ kind: "click", gain: 0.36, startHz: 2600, ampDecay: 100 }),
  ]),
  sound("lofi-kick", "Lo-Fi Dusty", "kick", true, 1.3, ["lofi", "hiphop"], ["dusty", "warm"], [
    L({ kind: "sine", gain: 0.86, startHz: 70, endHz: 44, pitchDecay: 7, ampDecay: 5, drive: 0.6, lp: 2800 }),
    L({ kind: "noise", gain: 0.08, ampDecay: 10, hp: 400, lp: 1800, noiseColor: 0.2 }),
  ]),
  sound("brush-kick", "Brush Kick", "kick", true, 1.0, ["jazz", "soft"], ["soft", "brush"], [
    L({ kind: "sine", gain: 0.55, startHz: 80, endHz: 50, pitchDecay: 10, ampDecay: 8, drive: 0.05 }),
    L({ kind: "noise", gain: 0.18, ampDecay: 14, hp: 600, lp: 3200, noiseColor: 0.5 }),
  ]),

  sound("808-snare", "808 Snare", "snare", false, 0.7, ["electronic", "hiphop"], ["snappy"], [
    L({ kind: "sine", gain: 0.35, startHz: 185, endHz: 140, pitchDecay: 20, ampDecay: 18 }),
    L({ kind: "noise", gain: 0.7, ampDecay: 14, hp: 800, lp: 9000, bp: 2200, q: 0.7, noiseColor: 1 }),
  ]),
  sound("909-snare", "909 Snare", "snare", false, 0.55, ["electronic", "house", "techno"], ["snappy", "classic"], [
    L({ kind: "sine", gain: 0.42, startHz: 220, endHz: 160, pitchDecay: 28, ampDecay: 22 }),
    L({ kind: "noise", gain: 0.78, ampDecay: 16, hp: 1200, lp: 10000, bp: 2800, q: 0.8, noiseColor: 1.2 }),
    L({ kind: "click", gain: 0.25, startHz: 5000, ampDecay: 90 }),
  ]),
  sound("studio-snare", "Studio Snare", "snare", true, 0.7, ["studio", "pop", "hiphop"], ["tight", "body"], [
    L({ kind: "sine", gain: 0.38, startHz: 196, endHz: 150, pitchDecay: 18, ampDecay: 16 }),
    L({ kind: "sine", gain: 0.16, startHz: 330, ampDecay: 22 }),
    L({ kind: "noise", gain: 0.62, ampDecay: 12, hp: 700, lp: 8000, bp: 1800, q: 0.6, noiseColor: 0.8 }),
    L({ kind: "click", gain: 0.22, startHz: 4200, ampDecay: 80 }),
  ]),
  sound("vintage-snare", "Vintage Snare", "snare", true, 0.85, ["studio", "hiphop"], ["warm", "fat"], [
    L({ kind: "sine", gain: 0.45, startHz: 170, endHz: 130, pitchDecay: 12, ampDecay: 12, drive: 0.3, lp: 5000 }),
    L({ kind: "noise", gain: 0.55, ampDecay: 10, hp: 500, lp: 4500, noiseColor: 0.5 }),
  ]),
  sound("brush-snare", "Brush Snare", "snare", true, 0.9, ["jazz", "soft", "indie"], ["soft", "brush"], [
    L({ kind: "noise", gain: 0.55, ampDecay: 8, hp: 400, lp: 6000, noiseColor: 0.6 }),
    L({ kind: "sine", gain: 0.12, startHz: 180, ampDecay: 14 }),
  ]),
  sound("trap-snare", "Trap Snare", "snare", false, 0.45, ["trap", "hiphop"], ["sharp", "thin"], [
    L({ kind: "sine", gain: 0.28, startHz: 240, ampDecay: 28 }),
    L({ kind: "noise", gain: 0.82, ampDecay: 20, hp: 1800, lp: 12000, bp: 4000, q: 0.9, noiseColor: 1.4 }),
  ]),
  sound("lofi-snare", "Lo-Fi Snare", "snare", true, 0.7, ["lofi", "hiphop"], ["dusty"], [
    L({ kind: "sine", gain: 0.32, startHz: 160, ampDecay: 14, lp: 2400, drive: 0.4 }),
    L({ kind: "noise", gain: 0.5, ampDecay: 9, hp: 400, lp: 2800, noiseColor: 0.3 }),
  ]),
  sound("pop-snare", "Pop Snare", "snare", true, 0.6, ["pop", "indie"], ["bright", "crack"], [
    L({ kind: "sine", gain: 0.3, startHz: 210, ampDecay: 18 }),
    L({ kind: "noise", gain: 0.72, ampDecay: 14, hp: 1000, lp: 11000, bp: 3200, q: 0.7, noiseColor: 1 }),
    L({ kind: "click", gain: 0.3, startHz: 6000, ampDecay: 100 }),
  ]),

  sound("808-clap", "808 Clap", "snare", false, 0.6, ["electronic", "hiphop"], ["clap"], [
    L({ kind: "noise", gain: 0.7, ampDecay: 22, hp: 600, lp: 8000, bp: 1400, q: 0.8, delayMs: 0, noiseColor: 1 }),
    L({ kind: "noise", gain: 0.55, ampDecay: 22, hp: 600, lp: 8000, bp: 1400, q: 0.8, delayMs: 12, noiseColor: 1 }),
    L({ kind: "noise", gain: 0.4, ampDecay: 18, hp: 800, lp: 7000, delayMs: 24, noiseColor: 1 }),
    L({ kind: "noise", gain: 0.22, ampDecay: 8, hp: 400, lp: 3000, delayMs: 18, noiseColor: 0.5 }),
  ]),
  sound("909-clap", "909 Clap", "snare", false, 0.5, ["house", "electronic"], ["clap", "classic"], [
    L({ kind: "noise", gain: 0.75, ampDecay: 26, hp: 800, lp: 9000, bp: 1800, q: 1, delayMs: 0 }),
    L({ kind: "noise", gain: 0.6, ampDecay: 26, hp: 800, lp: 9000, delayMs: 10 }),
    L({ kind: "noise", gain: 0.45, ampDecay: 20, delayMs: 19, hp: 1000, lp: 8000 }),
  ]),
  sound("studio-clap", "Studio Clap", "snare", true, 0.55, ["pop", "studio"], ["clap", "room"], [
    L({ kind: "noise", gain: 0.62, ampDecay: 18, hp: 700, lp: 7500, bp: 1600, q: 0.7, delayMs: 0 }),
    L({ kind: "noise", gain: 0.48, ampDecay: 16, delayMs: 14, hp: 900, lp: 7000 }),
    L({ kind: "noise", gain: 0.28, ampDecay: 10, delayMs: 28, hp: 500, lp: 4000 }),
  ]),
  sound("rimshot", "Rimshot", "snare", true, 0.28, ["studio", "hiphop", "pop"], ["rim", "tight"], [
    L({ kind: "sine", gain: 0.55, startHz: 420, endHz: 280, pitchDecay: 40, ampDecay: 32, drive: 0.2 }),
    L({ kind: "click", gain: 0.5, startHz: 2800, ampDecay: 70 }),
    L({ kind: "noise", gain: 0.22, ampDecay: 40, hp: 2000, lp: 7000 }),
  ]),
  sound("stick", "Stick Click", "snare", true, 0.18, ["studio", "pop"], ["click"], [
    L({ kind: "click", gain: 0.7, startHz: 3600, ampDecay: 90 }),
    L({ kind: "noise", gain: 0.25, ampDecay: 50, hp: 2500, lp: 9000 }),
  ]),

  sound("808-chh", "808 Closed Hat", "hat", false, 0.22, ["electronic", "hiphop", "trap"], ["metallic", "tight"], [
    L({ kind: "metallic", gain: 0.7, ampDecay: 38, hp: 7000, lp: 14000, bp: 9000, q: 0.6 }),
  ]),
  sound("808-ohh", "808 Open Hat", "hat", false, 0.9, ["electronic", "hiphop"], ["metallic", "open"], [
    L({ kind: "metallic", gain: 0.62, ampDecay: 7.5, hp: 5000, lp: 14000, bp: 8000, q: 0.5 }),
  ]),
  sound("909-chh", "909 Closed Hat", "hat", false, 0.16, ["house", "techno", "electronic"], ["tight", "classic"], [
    L({ kind: "noise", gain: 0.7, ampDecay: 48, hp: 6000, lp: 16000, bp: 10000, q: 0.8, noiseColor: 1.4 }),
  ]),
  sound("909-ohh", "909 Open Hat", "hat", false, 0.7, ["house", "techno"], ["open", "classic"], [
    L({ kind: "noise", gain: 0.65, ampDecay: 8, hp: 4500, lp: 15000, bp: 8000, q: 0.6, noiseColor: 1.2 }),
    L({ kind: "metallic", gain: 0.22, ampDecay: 7, hp: 6000, lp: 14000 }),
  ]),
  sound("studio-chh", "Studio Closed Hat", "hat", true, 0.14, ["studio", "pop", "hiphop"], ["acoustic", "tight"], [
    L({ kind: "noise", gain: 0.58, ampDecay: 55, hp: 5000, lp: 14000, noiseColor: 1 }),
    L({ kind: "metallic", gain: 0.18, ampDecay: 50, hp: 8000, lp: 16000 }),
  ]),
  sound("studio-ohh", "Studio Open Hat", "hat", true, 0.8, ["studio", "pop"], ["acoustic", "open"], [
    L({ kind: "noise", gain: 0.52, ampDecay: 7, hp: 4000, lp: 13000, noiseColor: 0.9 }),
    L({ kind: "metallic", gain: 0.28, ampDecay: 6.5, hp: 6000 }),
  ]),
  sound("trap-hat", "Trap Hat", "hat", false, 0.1, ["trap", "hiphop"], ["tick", "bright"], [
    L({ kind: "noise", gain: 0.75, ampDecay: 70, hp: 8000, lp: 18000, noiseColor: 1.6 }),
    L({ kind: "click", gain: 0.2, startHz: 9000, ampDecay: 120 }),
  ]),
  sound("lofi-hat", "Lo-Fi Hat", "hat", true, 0.18, ["lofi", "hiphop"], ["dusty", "dark"], [
    L({ kind: "noise", gain: 0.5, ampDecay: 36, hp: 2500, lp: 7000, noiseColor: 0.4, drive: 0.3 }),
  ]),
  sound("ride", "Ride Cymbal", "hat", true, 2.2, ["studio", "jazz", "pop"], ["ride", "metal"], [
    L({ kind: "metallic", gain: 0.45, ampDecay: 3.2, hp: 3000, lp: 14000, bp: 5500, q: 0.4 }),
    L({ kind: "noise", gain: 0.28, ampDecay: 2.8, hp: 4000, lp: 12000, noiseColor: 1.1 }),
    L({ kind: "sine", gain: 0.04, startHz: 420, ampDecay: 2.2 }),
  ]),
  sound("crash", "Crash", "hat", true, 2.8, ["studio", "pop", "rock"], ["crash", "wash"], [
    L({ kind: "noise", gain: 0.7, ampDecay: 2.4, hp: 1500, lp: 14000, noiseColor: 1.2 }),
    L({ kind: "metallic", gain: 0.4, ampDecay: 2.2, hp: 2500, lp: 16000 }),
    L({ kind: "noise", gain: 0.2, ampDecay: 1.6, hp: 600, lp: 4000, noiseColor: 0.6 }),
  ]),
  sound("brush-hat", "Brush Hat", "hat", true, 0.25, ["jazz", "soft"], ["soft"], [
    L({ kind: "noise", gain: 0.4, ampDecay: 18, hp: 2000, lp: 8000, noiseColor: 0.5 }),
  ]),

  sound("tom-hi", "Tom High", "tom", true, 0.7, ["studio", "pop"], ["tom"], [
    L({ kind: "sine", gain: 0.78, startHz: 220, endHz: 140, pitchDecay: 10, ampDecay: 8, drive: 0.15 }),
    L({ kind: "noise", gain: 0.16, ampDecay: 18, hp: 400, lp: 2500, noiseColor: 0.4 }),
    L({ kind: "click", gain: 0.18, startHz: 1800, ampDecay: 70 }),
  ]),
  sound("tom-mid", "Tom Mid", "tom", true, 0.85, ["studio", "pop"], ["tom"], [
    L({ kind: "sine", gain: 0.82, startHz: 148, endHz: 92, pitchDecay: 8, ampDecay: 6.5, drive: 0.18 }),
    L({ kind: "noise", gain: 0.14, ampDecay: 14, hp: 200, lp: 1800 }),
    L({ kind: "click", gain: 0.14, startHz: 1400, ampDecay: 60 }),
  ]),
  sound("tom-low", "Tom Low", "tom", true, 1.05, ["studio", "pop"], ["tom", "deep"], [
    L({ kind: "sine", gain: 0.88, startHz: 98, endHz: 62, pitchDecay: 7, ampDecay: 5.2, drive: 0.22 }),
    L({ kind: "noise", gain: 0.12, ampDecay: 12, hp: 80, lp: 1200 }),
    L({ kind: "click", gain: 0.1, startHz: 900, ampDecay: 50 }),
  ]),
  sound("808-tom", "808 Tom", "tom", false, 0.9, ["electronic", "hiphop"], ["electronic"], [
    L({ kind: "sine", gain: 0.9, startHz: 180, endHz: 80, pitchDecay: 11, ampDecay: 6, drive: 0.3 }),
    L({ kind: "click", gain: 0.12, startHz: 1200, ampDecay: 70 }),
  ]),

  sound("conga", "Conga", "perc", true, 0.55, ["latin", "world", "pop"], ["hand", "skin"], [
    L({ kind: "sine", gain: 0.7, startHz: 210, endHz: 150, pitchDecay: 18, ampDecay: 12, drive: 0.1 }),
    L({ kind: "noise", gain: 0.18, ampDecay: 22, hp: 600, lp: 4000, noiseColor: 0.5 }),
    L({ kind: "click", gain: 0.22, startHz: 1600, ampDecay: 65 }),
  ]),
  sound("bongo", "Bongo", "perc", true, 0.4, ["latin", "world"], ["hand", "bright"], [
    L({ kind: "sine", gain: 0.62, startHz: 320, endHz: 220, pitchDecay: 22, ampDecay: 16 }),
    L({ kind: "click", gain: 0.3, startHz: 2400, ampDecay: 80 }),
    L({ kind: "noise", gain: 0.12, ampDecay: 28, hp: 1000, lp: 5000 }),
  ]),
  sound("timbale", "Timbale", "perc", true, 0.45, ["latin", "world"], ["bright", "metal"], [
    L({ kind: "sine", gain: 0.5, startHz: 380, endHz: 260, pitchDecay: 24, ampDecay: 14 }),
    L({ kind: "metallic", gain: 0.22, ampDecay: 12, hp: 3000, lp: 10000 }),
    L({ kind: "click", gain: 0.28, startHz: 3000, ampDecay: 75 }),
  ]),
  sound("cowbell", "Cowbell", "perc", false, 0.5, ["electronic", "latin", "pop"], ["metal"], [
    L({ kind: "square", gain: 0.28, startHz: 540, ampDecay: 10, hp: 400, lp: 4000, drive: 0.2 }),
    L({ kind: "square", gain: 0.22, startHz: 800, ampDecay: 11, hp: 400, lp: 5000 }),
    L({ kind: "click", gain: 0.18, startHz: 2200, ampDecay: 50 }),
  ]),
  sound("shaker", "Shaker", "perc", true, 0.28, ["pop", "latin", "house"], ["shake"], [
    L({ kind: "noise", gain: 0.55, ampDecay: 16, hp: 4000, lp: 14000, noiseColor: 1.3, attack: 0.004 }),
  ]),
  sound("tambourine", "Tambourine", "perc", true, 0.4, ["pop", "indie"], ["jingle"], [
    L({ kind: "noise", gain: 0.4, ampDecay: 14, hp: 3500, lp: 12000, noiseColor: 1.1 }),
    L({ kind: "metallic", gain: 0.28, ampDecay: 12, hp: 5000, lp: 14000 }),
  ]),
  sound("clave", "Clave", "perc", true, 0.2, ["latin", "world"], ["wood"], [
    L({ kind: "sine", gain: 0.45, startHz: 2100, ampDecay: 45 }),
    L({ kind: "click", gain: 0.55, startHz: 2800, ampDecay: 80 }),
    L({ kind: "sine", gain: 0.15, startHz: 1400, ampDecay: 40 }),
  ]),
  sound("surdo", "Surdo", "perc", true, 1.1, ["brazilian", "world"], ["deep", "skin"], [
    L({ kind: "sine", gain: 0.9, startHz: 72, endHz: 48, pitchDecay: 8, ampDecay: 5, drive: 0.15 }),
    L({ kind: "noise", gain: 0.12, ampDecay: 16, hp: 80, lp: 600 }),
    L({ kind: "click", gain: 0.14, startHz: 700, ampDecay: 50 }),
  ]),
  sound("agogo", "Agogo", "perc", true, 0.4, ["brazilian", "world"], ["metal"], [
    L({ kind: "sine", gain: 0.4, startHz: 880, ampDecay: 9 }),
    L({ kind: "sine", gain: 0.28, startHz: 1320, ampDecay: 10 }),
    L({ kind: "click", gain: 0.2, startHz: 4000, ampDecay: 70 }),
  ]),
  sound("djembe", "Djembe", "perc", true, 0.55, ["afro", "world"], ["hand", "skin"], [
    L({ kind: "sine", gain: 0.65, startHz: 160, endHz: 110, pitchDecay: 14, ampDecay: 10 }),
    L({ kind: "noise", gain: 0.25, ampDecay: 16, hp: 500, lp: 3500, noiseColor: 0.6 }),
    L({ kind: "click", gain: 0.25, startHz: 2000, ampDecay: 70 }),
  ]),
  sound("taiko", "Taiko", "perc", true, 1.4, ["cinematic", "world"], ["epic", "deep"], [
    L({ kind: "sine", gain: 0.92, startHz: 64, endHz: 40, pitchDecay: 6, ampDecay: 3.5, drive: 0.25 }),
    L({ kind: "noise", gain: 0.28, ampDecay: 8, hp: 100, lp: 1200, noiseColor: 0.3 }),
    L({ kind: "click", gain: 0.2, startHz: 800, ampDecay: 40 }),
  ]),
  sound("impact", "Cinematic Impact", "fx", false, 1.8, ["cinematic"], ["impact", "dark"], [
    L({ kind: "sine", gain: 0.85, startHz: 110, endHz: 32, pitchDecay: 5, ampDecay: 2.8, drive: 0.5 }),
    L({ kind: "noise", gain: 0.45, ampDecay: 4, hp: 80, lp: 2000, noiseColor: 0.4 }),
    L({ kind: "noise", gain: 0.2, ampDecay: 2.2, hp: 2000, lp: 8000, delayMs: 30 }),
  ]),
  sound("riser-tick", "FX Tick", "fx", false, 0.2, ["electronic", "pop"], ["tick"], [
    L({ kind: "click", gain: 0.6, startHz: 5000, ampDecay: 90 }),
    L({ kind: "noise", gain: 0.25, ampDecay: 40, hp: 4000, lp: 12000 }),
  ]),
  sound("vinyl-crackle", "Vinyl Crackle", "fx", true, 0.35, ["lofi", "hiphop"], ["dusty"], [
    L({ kind: "noise", gain: 0.35, ampDecay: 12, hp: 800, lp: 6000, noiseColor: 0.8 }),
    L({ kind: "click", gain: 0.15, startHz: 1800, ampDecay: 60 }),
  ]),
];

export const SOUND_BY_ID: Record<string, SoundDef> = Object.fromEntries(
  SOUND_LIBRARY.map((s) => [s.id, s]),
);

function kit(
  id: string,
  name: string,
  category: string,
  genre: string,
  character: string,
  acoustic: boolean,
  slots: KitDef["slots"],
): KitDef {
  return { id, name, category, genre, character, acoustic, slots };
}

const S = (soundId: string, extra: Omit<KitDef["slots"][number], "soundId"> = {}) => ({ soundId, ...extra });

export const KIT_LIBRARY: KitDef[] = [
  kit("dry-studio", "Dry Studio", "Studio", "pop", "tight", true, [
    S("studio-kick", { volume: 0.9, reverbSend: 0.02 }),
    S("acoustic-kick", { volume: 0.55, pitch: -3, reverbSend: 0 }),
    S("studio-snare", { volume: 0.82, reverbSend: 0.18 }),
    S("studio-clap", { volume: 0.5, reverbSend: 0.28 }),
    S("rimshot", { volume: 0.7 }),
    S("studio-chh", { volume: 0.58, chokeGroup: 1 }),
    S("studio-ohh", { volume: 0.5, chokeGroup: 1, reverbSend: 0.2 }),
    S("ride", { volume: 0.45, reverbSend: 0.22 }),
    S("crash", { volume: 0.55, reverbSend: 0.4 }),
    S("tom-hi", { pan: 0.25, reverbSend: 0.16 }),
    S("tom-mid", { reverbSend: 0.16 }),
    S("tom-low", { pan: -0.22, reverbSend: 0.16 }),
    S("conga", { pan: -0.3 }),
    S("tambourine", { pan: 0.35, volume: 0.45 }),
    S("shaker", { volume: 0.4 }),
    S("riser-tick", { volume: 0.5 }),
  ]),
  kit("vintage-studio", "Vintage Studio", "Studio", "hiphop", "warm", true, [
    S("vintage-kick"),
    S("lofi-kick", { volume: 0.4, pitch: -5 }),
    S("vintage-snare", { reverbSend: 0.3 }),
    S("808-clap", { volume: 0.4, reverbSend: 0.35 }),
    S("rimshot"),
    S("lofi-hat", { chokeGroup: 1 }),
    S("studio-ohh", { chokeGroup: 1, cutoff: 0.55 }),
    S("ride", { cutoff: 0.6 }),
    S("crash", { cutoff: 0.65 }),
    S("tom-hi", { pitch: -2 }),
    S("tom-mid", { pitch: -2 }),
    S("tom-low", { pitch: -1 }),
    S("clave"),
    S("conga"),
    S("shaker"),
    S("vinyl-crackle", { volume: 0.35 }),
  ]),
  kit("big-room", "Big Room", "Studio", "pop", "huge", true, [
    S("acoustic-kick", { drive: 0.35, reverbSend: 0.08 }),
    S("house-kick", { volume: 0.5 }),
    S("pop-snare", { reverbSend: 0.42 }),
    S("studio-clap", { reverbSend: 0.5 }),
    S("stick"),
    S("studio-chh", { chokeGroup: 1 }),
    S("studio-ohh", { chokeGroup: 1, reverbSend: 0.3 }),
    S("ride"),
    S("crash", { reverbSend: 0.55 }),
    S("tom-hi", { reverbSend: 0.28 }),
    S("tom-mid", { reverbSend: 0.28 }),
    S("tom-low", { reverbSend: 0.28 }),
    S("tambourine"),
    S("shaker"),
    S("cowbell", { volume: 0.35 }),
    S("impact", { volume: 0.6 }),
  ]),
  kit("brush-soft", "Brush / Soft", "Studio", "jazz", "soft", true, [
    S("brush-kick", { volume: 0.8 }),
    S("vintage-kick", { volume: 0.3, pitch: -4 }),
    S("brush-snare", { reverbSend: 0.35 }),
    S("studio-clap", { volume: 0.25 }),
    S("stick", { volume: 0.55 }),
    S("brush-hat", { chokeGroup: 1 }),
    S("studio-ohh", { chokeGroup: 1, decay: 0.7, volume: 0.4 }),
    S("ride", { volume: 0.55, reverbSend: 0.3 }),
    S("crash", { volume: 0.35 }),
    S("tom-hi", { volume: 0.55 }),
    S("tom-mid", { volume: 0.55 }),
    S("tom-low", { volume: 0.6 }),
    S("shaker"),
    S("tambourine"),
    S("clave", { volume: 0.35 }),
    S("vinyl-crackle"),
  ]),
  kit("kit-808", "808", "Electronic", "hiphop", "analog", false, [
    S("808-kick"),
    S("808-sub", { volume: 0.7 }),
    S("808-snare"),
    S("808-clap", { reverbSend: 0.32 }),
    S("rimshot", { pitch: 3 }),
    S("808-chh", { chokeGroup: 1 }),
    S("808-ohh", { chokeGroup: 1 }),
    S("ride", { cutoff: 0.7, volume: 0.3 }),
    S("crash", { volume: 0.4 }),
    S("808-tom", { pitch: 5 }),
    S("808-tom"),
    S("808-tom", { pitch: -5 }),
    S("cowbell"),
    S("clave"),
    S("shaker"),
    S("riser-tick"),
  ]),
  kit("kit-909", "909", "Electronic", "house", "classic", false, [
    S("909-kick"),
    S("909-kick-hard", { volume: 0.45, pitch: -2 }),
    S("909-snare"),
    S("909-clap", { reverbSend: 0.4 }),
    S("rimshot"),
    S("909-chh", { chokeGroup: 1 }),
    S("909-ohh", { chokeGroup: 1 }),
    S("ride", { volume: 0.35 }),
    S("crash", { volume: 0.45 }),
    S("tom-hi", { pitch: 2 }),
    S("tom-mid"),
    S("tom-low"),
    S("cowbell", { volume: 0.4 }),
    S("clave"),
    S("shaker"),
    S("riser-tick"),
  ]),
  kit("classic-analog", "Classic Analog", "Electronic", "electronic", "analog", false, [
    S("808-kick-punch"),
    S("909-kick", { volume: 0.5 }),
    S("909-snare"),
    S("808-clap"),
    S("stick"),
    S("808-chh", { chokeGroup: 1 }),
    S("909-ohh", { chokeGroup: 1 }),
    S("ride", { volume: 0.3 }),
    S("crash", { volume: 0.4 }),
    S("808-tom", { pitch: 4 }),
    S("808-tom"),
    S("808-tom", { pitch: -7 }),
    S("cowbell"),
    S("agogo"),
    S("shaker"),
    S("impact", { volume: 0.4 }),
  ]),
  kit("modern-electronic", "Modern Electronic", "Electronic", "pop", "modern", false, [
    S("house-kick", { drive: 0.4 }),
    S("808-sub", { volume: 0.55 }),
    S("trap-snare", { reverbSend: 0.25 }),
    S("909-clap", { reverbSend: 0.45 }),
    S("rimshot"),
    S("trap-hat", { chokeGroup: 1 }),
    S("909-ohh", { chokeGroup: 1 }),
    S("ride", { volume: 0.28 }),
    S("crash"),
    S("tom-hi", { pitch: 4 }),
    S("tom-mid"),
    S("tom-low"),
    S("shaker"),
    S("tambourine"),
    S("cowbell", { volume: 0.3 }),
    S("impact"),
  ]),
  kit("deep-house", "Deep House", "Electronic", "house", "warm", false, [
    S("house-kick", { decay: 0.55 }),
    S("808-sub", { volume: 0.4, pitch: -2 }),
    S("909-clap", { reverbSend: 0.48 }),
    S("studio-clap", { volume: 0.35, reverbSend: 0.4 }),
    S("rimshot", { volume: 0.4 }),
    S("909-chh", { chokeGroup: 1, volume: 0.5 }),
    S("909-ohh", { chokeGroup: 1, reverbSend: 0.28 }),
    S("ride", { volume: 0.32, reverbSend: 0.3 }),
    S("crash", { volume: 0.35 }),
    S("tom-hi"),
    S("tom-mid"),
    S("tom-low"),
    S("shaker", { volume: 0.45 }),
    S("conga", { volume: 0.4 }),
    S("tambourine"),
    S("riser-tick"),
  ]),
  kit("techno", "Techno", "Electronic", "techno", "hard", false, [
    S("909-kick-hard"),
    S("909-kick", { volume: 0.35, pitch: -4 }),
    S("909-snare", { volume: 0.7 }),
    S("909-clap", { volume: 0.55 }),
    S("stick"),
    S("909-chh", { chokeGroup: 1, volume: 0.7 }),
    S("909-ohh", { chokeGroup: 1 }),
    S("ride", { volume: 0.4 }),
    S("crash", { volume: 0.35 }),
    S("tom-low", { pitch: -4 }),
    S("808-tom", { pitch: -8 }),
    S("taiko", { volume: 0.4 }),
    S("cowbell", { volume: 0.3 }),
    S("clave"),
    S("shaker", { volume: 0.25 }),
    S("impact"),
  ]),
  kit("classic-hiphop", "Classic Hip-Hop", "Hip-Hop", "hiphop", "boom", true, [
    S("vintage-kick"),
    S("808-sub", { volume: 0.55 }),
    S("vintage-snare", { reverbSend: 0.28 }),
    S("808-clap", { volume: 0.45 }),
    S("rimshot"),
    S("studio-chh", { chokeGroup: 1 }),
    S("808-ohh", { chokeGroup: 1, volume: 0.45 }),
    S("ride", { volume: 0.28 }),
    S("crash", { volume: 0.4 }),
    S("tom-hi"),
    S("tom-mid"),
    S("tom-low"),
    S("bongo"),
    S("conga"),
    S("shaker"),
    S("vinyl-crackle"),
  ]),
  kit("lofi-hiphop", "Lo-Fi Hip-Hop", "Hip-Hop", "lofi", "dusty", true, [
    S("lofi-kick"),
    S("vintage-kick", { volume: 0.35, pitch: -6 }),
    S("lofi-snare", { reverbSend: 0.38 }),
    S("studio-clap", { volume: 0.3, cutoff: 0.45 }),
    S("rimshot", { cutoff: 0.5 }),
    S("lofi-hat", { chokeGroup: 1 }),
    S("studio-ohh", { chokeGroup: 1, cutoff: 0.48 }),
    S("ride", { cutoff: 0.5, volume: 0.3 }),
    S("crash", { cutoff: 0.5, volume: 0.3 }),
    S("tom-hi", { cutoff: 0.55 }),
    S("tom-mid"),
    S("tom-low"),
    S("shaker", { cutoff: 0.5 }),
    S("vinyl-crackle", { volume: 0.5 }),
    S("clave", { volume: 0.3 }),
    S("brush-snare", { volume: 0.35 }),
  ]),
  kit("boom-bap", "Boom Bap", "Hip-Hop", "hiphop", "boom", true, [
    S("studio-kick", { punch: 0.7, decay: 0.6 }),
    S("808-sub", { volume: 0.45 }),
    S("studio-snare", { snap: 0.7, reverbSend: 0.22 }),
    S("808-clap", { volume: 0.32 }),
    S("rimshot"),
    S("studio-chh", { chokeGroup: 1, volume: 0.55 }),
    S("studio-ohh", { chokeGroup: 1 }),
    S("ride", { volume: 0.25 }),
    S("crash", { volume: 0.4 }),
    S("tom-hi"),
    S("tom-mid"),
    S("tom-low"),
    S("conga"),
    S("bongo"),
    S("shaker"),
    S("vinyl-crackle", { volume: 0.28 }),
  ]),
  kit("modern-hiphop", "Modern Hip-Hop", "Hip-Hop", "hiphop", "modern", false, [
    S("808-kick-punch"),
    S("808-sub"),
    S("trap-snare"),
    S("808-clap", { reverbSend: 0.3 }),
    S("rimshot"),
    S("trap-hat", { chokeGroup: 1 }),
    S("808-ohh", { chokeGroup: 1 }),
    S("ride", { volume: 0.22 }),
    S("crash", { volume: 0.4 }),
    S("808-tom", { pitch: 7 }),
    S("808-tom"),
    S("808-tom", { pitch: -7 }),
    S("shaker"),
    S("clave"),
    S("cowbell", { volume: 0.25 }),
    S("riser-tick"),
  ]),
  kit("trap", "Trap", "Hip-Hop", "trap", "dark", false, [
    S("808-kick", { decay: 0.85 }),
    S("808-sub", { volume: 0.85 }),
    S("trap-snare", { reverbSend: 0.28 }),
    S("808-clap", { volume: 0.4 }),
    S("stick"),
    S("trap-hat", { chokeGroup: 1, volume: 0.7 }),
    S("808-ohh", { chokeGroup: 1 }),
    S("ride", { volume: 0.2 }),
    S("crash", { volume: 0.45 }),
    S("808-tom", { pitch: 8 }),
    S("808-tom"),
    S("808-tom", { pitch: -10 }),
    S("shaker", { volume: 0.3 }),
    S("riser-tick"),
    S("clave", { volume: 0.25 }),
    S("impact"),
  ]),
  kit("modern-pop", "Modern Pop", "Pop", "pop", "bright", true, [
    S("studio-kick", { punch: 0.65 }),
    S("house-kick", { volume: 0.4 }),
    S("pop-snare", { reverbSend: 0.3 }),
    S("studio-clap", { reverbSend: 0.4 }),
    S("stick"),
    S("studio-chh", { chokeGroup: 1 }),
    S("studio-ohh", { chokeGroup: 1 }),
    S("ride", { volume: 0.32 }),
    S("crash"),
    S("tom-hi"),
    S("tom-mid"),
    S("tom-low"),
    S("tambourine", { volume: 0.5 }),
    S("shaker"),
    S("clave", { volume: 0.3 }),
    S("riser-tick"),
  ]),
  kit("indie-pop", "Indie Pop", "Pop", "indie", "airy", true, [
    S("acoustic-kick"),
    S("brush-kick", { volume: 0.35 }),
    S("pop-snare", { reverbSend: 0.36 }),
    S("studio-clap", { volume: 0.35 }),
    S("rimshot"),
    S("studio-chh", { chokeGroup: 1 }),
    S("studio-ohh", { chokeGroup: 1, reverbSend: 0.28 }),
    S("ride", { volume: 0.4, reverbSend: 0.3 }),
    S("crash", { volume: 0.45 }),
    S("tom-hi"),
    S("tom-mid"),
    S("tom-low"),
    S("tambourine"),
    S("shaker"),
    S("bongo", { volume: 0.35 }),
    S("vinyl-crackle", { volume: 0.2 }),
  ]),
  kit("electro-pop", "Electro Pop", "Pop", "pop", "electronic", false, [
    S("house-kick"),
    S("808-kick-punch", { volume: 0.4 }),
    S("trap-snare"),
    S("909-clap", { reverbSend: 0.42 }),
    S("stick"),
    S("trap-hat", { chokeGroup: 1 }),
    S("909-ohh", { chokeGroup: 1 }),
    S("ride", { volume: 0.25 }),
    S("crash"),
    S("808-tom", { pitch: 5 }),
    S("tom-mid"),
    S("tom-low"),
    S("shaker"),
    S("tambourine"),
    S("cowbell", { volume: 0.28 }),
    S("impact", { volume: 0.45 }),
  ]),
  kit("latin", "Latin", "World", "latin", "live", true, [
    S("acoustic-kick", { volume: 0.7 }),
    S("surdo", { volume: 0.45 }),
    S("rimshot", { volume: 0.7 }),
    S("studio-clap", { volume: 0.35 }),
    S("stick"),
    S("studio-chh", { chokeGroup: 1, volume: 0.45 }),
    S("studio-ohh", { chokeGroup: 1, volume: 0.4 }),
    S("ride", { volume: 0.3 }),
    S("crash", { volume: 0.3 }),
    S("tom-hi"),
    S("conga"),
    S("tom-low"),
    S("conga", { pitch: 3 }),
    S("bongo"),
    S("timbale"),
    S("clave"),
  ]),
  kit("brazilian", "Brazilian", "World", "brazilian", "live", true, [
    S("surdo"),
    S("acoustic-kick", { volume: 0.4 }),
    S("rimshot"),
    S("studio-clap", { volume: 0.3 }),
    S("stick"),
    S("studio-chh", { chokeGroup: 1 }),
    S("studio-ohh", { chokeGroup: 1 }),
    S("ride", { volume: 0.25 }),
    S("crash", { volume: 0.28 }),
    S("tom-hi"),
    S("tom-mid"),
    S("tom-low"),
    S("agogo"),
    S("tambourine"),
    S("shaker"),
    S("clave"),
  ]),
  kit("afro", "Afro", "World", "afro", "live", true, [
    S("djembe", { pitch: -4, volume: 0.8 }),
    S("surdo", { volume: 0.5 }),
    S("djembe", { pitch: 5 }),
    S("studio-clap", { volume: 0.25 }),
    S("stick"),
    S("studio-chh", { chokeGroup: 1, volume: 0.4 }),
    S("studio-ohh", { chokeGroup: 1 }),
    S("ride", { volume: 0.22 }),
    S("crash", { volume: 0.28 }),
    S("tom-hi"),
    S("tom-mid"),
    S("tom-low"),
    S("djembe"),
    S("bongo"),
    S("shaker"),
    S("agogo"),
  ]),
  kit("cinematic", "Cinematic Percussion", "World", "cinematic", "epic", true, [
    S("taiko"),
    S("impact", { volume: 0.7 }),
    S("studio-snare", { reverbSend: 0.5, volume: 0.7 }),
    S("909-clap", { reverbSend: 0.45 }),
    S("rimshot"),
    S("studio-chh", { chokeGroup: 1, volume: 0.3 }),
    S("studio-ohh", { chokeGroup: 1, volume: 0.3 }),
    S("ride", { reverbSend: 0.4 }),
    S("crash", { reverbSend: 0.6, volume: 0.7 }),
    S("tom-hi", { reverbSend: 0.35 }),
    S("tom-mid", { reverbSend: 0.35 }),
    S("tom-low", { reverbSend: 0.4 }),
    S("djembe"),
    S("surdo"),
    S("shaker", { volume: 0.3 }),
    S("impact"),
  ]),
];

export const KIT_BY_ID: Record<string, KitDef> = Object.fromEntries(KIT_LIBRARY.map((k) => [k.id, k]));

export function soundsForFamily(family: DrumFamily): SoundDef[] {
  return SOUND_LIBRARY.filter((s) => s.family === family);
}

export function nextSoundId(current: string, dir: 1 | -1, family?: DrumFamily): string {
  const pool = family ? soundsForFamily(family) : SOUND_LIBRARY;
  const idx = pool.findIndex((s) => s.id === current);
  if (idx < 0) return pool[0]?.id ?? current;
  const n = (idx + dir + pool.length) % pool.length;
  return pool[n]!.id;
}
